wandb_version: 1

architecture:
  desc: null
  value: resnet
train_dataset:
  desc: null
  value: flowers
val_dataset:
  desc: null
  value: stl10
train_batch_size:
  desc: null
  value: 128
train_epochs:
  desc: null
  value: 100
val_epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702020679.83221
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
